name: SurvivalCore
version: ${project.version}
api-version: 1.16
main: fr.iban.survivalcore.SurvivalCorePlugin
authors: [Iban]
description: Core du projet SpartaCube
softdepend: [Lands, CoreProtect, BetterRTP]
depend: [LuckPerms, Essentials, Core, Vault]

commands:
  site:
  discord:
  vote:
  map:
  stoptuto:
  addhomes:
  grades:
  feed:
  repair:
  givetools:
  annonce:
  pvp:
  survivalcore:
  dolphin:
    aliases: [dophin]
