name: SurvivalCore
version: ${project.version}
api-version: 1.16
main: fr.iban.survivalcore.SurvivalCorePlugin
authors: [Iban]
description: Core du projet SpartaCube
softdepend: [dynmap, Lands, Vault, CoreProtect]
depend: [LuckPerms, Essentials, Core]

commands:
  site:
  discord:
  vote:
  map:
  stoptuto:
  addhomes:
  grades:
  boost:
  feed:
  repair:
  givetools:
  annonce:
  pvp:
  survivalcore:
  dolphin:
    aliases: [dophin]
