name: Core
version: ${project.version}
main: fr.iban.bukkitcore.CoreBukkitPlugin
api-version: 1.16
authors: [ Iban ]
softdepend: [Essentials, Vault]

commands:
  site:
  discord:
  vote:
  grades:
  ressources:
  serveur:
  options:
  survie:
  core:
    permission: servercore.papercore.reload
  recompenses:
  addtabcomplete:
  abbc:
    permission: servercore.abbc
  tp:
  tpa:
  tpno:
    aliases:
      - tpdeny
  tpyes:
    aliases:
      - tpaccept
  tphere:
    aliases:
      - s
  tpahere:
  bungeebroadcast:
    aliases:
      - bbc
    permission: servercore.bbc
