redis:
  host: 172.18.0.1
  port: 6380
  password: Zkvo5le1
  clientName: Serveur_mc

database:
  host: 172.18.0.1
  port: 3306
  user: user
  dbname: dbname
  password: password

motd: "&2&lPrimal&a&lCraft &8&l> &f&lServeur survie 1.17.1&r\n&7Claims &8● &7Shops &8● &7Shops joueurs &8●&7 Métiers &8● &7Warps joueurs"
chat-format: "%premium% %lp_suffix% %lp_prefix% %player% %lp_suffix% ➤"

tabcomplete:
  global:
    - sethome
    - delhome
    - spawn
    - warp
    - warps
    - lands
    - land
    - classement
    - niveau
    - level
    - kit
    - kits
    - vote
    - map
    - boutique
    - site
    - discord
    - repair
    - ec
    - tptoggle
    - ignore
    - ignorelist
  moderation:
    - mod
    - ban
    - tempban
    - mute
    - tempmute
    - kick