redis:
  host: 172.18.0.1
  port: 6380
  password: Zkvo5le1
  clientName: Serveur_mc

database:
  host: 172.18.0.1
  port: 3306
  user: user
  dbname: dbname
  password: password

motd:
  - "motd"
chat-format: '#feca57%premium%&r%lp_suffix%%lp_prefix% %player% %lp_suffix% ➤ &r'
ping-color: '#fdcb6e'

tabcomplete:
  global:
    - tpa
    - tpahere
    - tpyes
    - tpaccept
    - back
    - msg
    - r
    - reply
    - oab
    - find
  moderation:
    - oab
    - tphere
    - ban
    - tempban
    - tempmute
    - history
    - warn
    - tempwarn
    - unban
    - unmute
    - tp
    - s
    - server
    - sctoggle
    - kick
    - announceevent
    - chat