file-version: 1.0

redis:
    host: 172.18.0.1
    port: 6380
    password: pass
    clientName: Serveur_mc

database:
    host: 172.18.0.1
    port: 3306
    user: user
    dbname: dbname
    password: password

#sql or redis
messenger: redis

motd:
    - "motd"
chat-format: |
    [&7[%levels_level%&7] &#feca57&%premium%&r%vault_suffix%%vault_prefix% %player% %vault_suffix% ➤ &r](Informations:
    
    &#55efc4&Argent: &f%bungeeeconomy_balance%
    &#55efc4&Guilde: &f%guilds_name%
    
    &7Clic pour envoyer un message suggest_command=/msg %player% )
staff-chat-format: '&8[&3&lStaff&8] &#feca57&%premium%&r%vault_suffix%%vault_prefix% %player% %vault_suffix% ➤ &r'
ping-prefix: '&#fdcb6e&@'

messages:
    site: "url du site"
    vote: "url pour voter"
    discord: "url du discord"
    grades: "url des info sur les grades"